### PR TITLE
Migrate CI/CD to GitHub actions

### PR DESCRIPTION
**Pull request by mirand863**
- [x] Add codecov deployment (if possible)
- [x] Update coverage badge
- [x] Update pipeline to run only on the main branch
- [ ] Update recipe on bioconda

### CODE REVIEW

**Comment by mirand863** [comment]
@hoelzer The GitHub actions template I have does not use docker, hence there is a problem with some tests failing because `pblat` cannot be installed with `pip`. I just added a simple check to verify if `pblat` is installed. If it is, then all tests are executed, otherwise the ones that fail are skipped. I also added some pre-commit hooks to run `black` and some other formatting stuff to make the code neater. Tomorrow I will add the deployment steps for dockerhub, pypi and bioconda.

**Comment by mirand863** [comment]
Hi @hoelzer,

> Hey @mirand863 great thanks for the super fast transition!
> 
> > However, the GitHub actions template I have does not use `docker`, hence there is a problem with some tests failing because `pblat` cannot be installed with `pip`. I just added a simple check to verify if `pblat` is installed. If it is, then all tests are executed, otherwise the ones that fail are skipped.
> 
> Alright. But I don't get it: `pblat` can not be installed via `pip` because you dont use `docker` in your GitHub action?

What I meant is that `pblat` can only be easily installed with `conda` and conda was being installed on GitLab through a docker container. However, I am not sure how to use docker containers here, so I am skipping `pblat` tests. All the other dependencies can be installed with `pip`, except `pblat`.

> 
> > Tomorrow I will add the deployment steps for dockerhub, pypi and bioconda.
> 
> Great. Let me know if you need any keys.
> 
> And regarding dockerhub, if it's more work then it might not be that necessary. We anyway have now some GitHub actions running in this account to deploy several containers for different tools. And there we also set one up for `president` using the `conda` installation:
> 
> https://hub.docker.com/r/rkimf1/president/tags

Good to know I do not need to deploy to docker. However, I am trying to update the test coverage badge, and the easiest way to do it would be to use Codecov. I just requested access for that purpose, but if you would not like to use third-parties just let me know.

**Comment by hoelzer** [comment]
@mirand863 alright, I see! Let me quickly check regarding third-party tools access! I will let you know asap

**Comment by hoelzer** [comment]
@mirand863 all good for Codecov! I will approve the tool in a min

**Comment by mirand863** [comment]
> @mirand863 all good for Codecov! I will approve the tool in a min

@hoelzer great! Everything is configured. Codecov is working, the upload to pypi as well and I just updated the recipe on bioconda, but I am still waiting for someone to approve it and merge. This PR is good to review in the meantime. If you approve, I can merge as soon as the recipe on bioconda is updated. Now the update workflow is simplified... You only need to merge a pull request, then the coverage badge will be updated via codecov, the package on pypi is updated as well and the recipe on bioconda is updated automatically by the bot after the update on pypi. You don't need to create releases anymore, since bumping versions is also automatic. What you do need to do is add #major or #minor to the PR title if you want something other than a patch bump. I also wrote some instructions on CONTRIBUTING.md in case you need to revisit this in the future.

**Comment by hoelzer** [comment]
@mirand863 a.w.e.s.o.m.e! Thanks a lot for the fast transition and that sounds all really good! I will give the PR a look asap! And then as soon as the bioconda recipe is confirmed, you can merge the PR.

**Pull request merged**
